// <auto-generated />
using System;
using CalculadoraEmocional.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculadoraEmocional.Api.Migrations
{
    [DbContext(typeof(CalculadoraEmocionalContext))]
    [Migration("20251122180932_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculadoraEmocional.Api.Entities.Checkin", b =>
                {
                    b.Property<long>("IdCheckin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_checkin");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCheckin"));

                    b.Property<DateTime>("DataCheckin")
                        .HasColumnType("datetime2")
                        .HasColumnName("dt_checkin");

                    b.Property<int>("Foco")
                        .HasColumnType("int")
                        .HasColumnName("vl_foco");

                    b.Property<decimal?>("HorasTrabalhadas")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("horas_trabalhadas");

                    b.Property<int>("Humor")
                        .HasColumnType("int")
                        .HasColumnName("vl_humor");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<int?>("MinutosPausas")
                        .HasColumnType("int")
                        .HasColumnName("minutos_pausas");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_observacoes");

                    b.Property<string>("Origem")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("origem");

                    b.Property<string>("Tags")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tags");

                    b.HasKey("IdCheckin");

                    b.ToTable("T_GS_CHECKIN", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
